### PR TITLE
Edge anomaly detection component

### PR DESCRIPTION
**Pull request by stefan-bergstein**
1. 1st version of the component
2. installation of open data hub

### CODE REVIEW

**Comment by DanielFroehlich** [comment]
question: why is the odh-instance in the iot-consumer component manifest? should that also be in the  new "edge-anomaly-detection" component?

**Comment by DanielFroehlich** [comment]
next question:  what is the rationale behind the component name "edge-anomaly-detctetion"? Currently, all components start with "iot-....", and we have a lot of flexibility where we actually deploy this component. I dont like the "edge" in the name, because we might deploy it nearedge, faredge, or even in the dc. suggest to name it "iot-anomaly-detection-ml"

**Comment by DanielFroehlich** [comment]
as per chat, my comments will be fixed by stefan, closing this one without merge.

**Comment by stefan-bergstein** [comment]
addressed comments and a few other issues

**Comment by ortwinschneider** [comment]
Looks good to me.
Just one question: There is a seldon-deployment-crd.yaml in the components folder.
Wondering if the CRD should be better placed in the namepsaces_and_operators_.... folder?
Normally operators introduce new CRs through CRDs
(CRDs close to operator and CRs close to app components)
What do you think?

**Comment by stefan-bergstein** [comment]
Re: Seldon CRD. 
Open Data Hub is suboptimal. It does not install all CRDs. The Seldon CRD is only needed for the Anomaly Detection. Therefore I  put it there.

**Comment by wrichter** [comment]
The namespaces_and_operator Dir is there to instantiate operators in a separate step before installing CRs based on the operator CRD. OLM does instantiate CRDs asynchronously, therefore the CRDs are not instantaneously available (and the k8s API Server will reject CRs for them for a short while). If you bring your own CRD that shouldn’t matter

**Pull request merged**
